name: release build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the tag name
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push with ui
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ secrets.GH_USERNAME }}/kopia_rclone_docker:latest
            ghcr.io/${{ secrets.GH_USERNAME }}/kopia_rclone_docker:${{ steps.get_tag.outputs.TAG }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile

      - name: Build and push without ui
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ secrets.GH_USERNAME }}/kopia_rclone_docker:latest-noui
            ghcr.io/${{ secrets.GH_USERNAME }}/kopia_rclone_docker:${{ steps.get_tag.outputs.TAG }}-noui
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          build-args: |
            KOPIA_BUILD_TYPE=noui
