name: weeekly build

on:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to Github container registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image and push to Github container registry
        run: |
          docker buildx build \
            --push \
            --build-arg RCLONE_BRANCH=master \
            --build-arg KOPIA_BRANCH=master \
            --tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/kopia_rclone_docker:weekly \
            --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
            .

      - name: build the no ui image and push to Github container registry
        run: |
          docker buildx build \
            --push \
            --build-arg RCLONE_BRANCH=master \
            --build-arg KOPIA_BRANCH=master \
            --build-arg KOPIA_BUILD_TYPE=noui \
            --tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/kopia_rclone_docker:weekly-noui \
            --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
            .
